// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Constants
{
    public const string event_testovaci_udalost = "CgkIhc_Q_OkGEAIQAg"; // <GPGSID>
    public const string achievement_treti = "CgkIhc_Q_OkGEAIQBQ"; // <GPGSID>
    public const string achievement_firstten = "CgkIhc_Q_OkGEAIQAw"; // <GPGSID>
    public const string achievement_druhy = "CgkIhc_Q_OkGEAIQBA"; // <GPGSID>
    public const string package_name = "gg.iameska.jump"; // <GPGSID>
    public const string achievement_ctvrty = "CgkIhc_Q_OkGEAIQBg"; // <GPGSID>
    public const string achievement_paty = "CgkIhc_Q_OkGEAIQBw"; // <GPGSID>

    public const string TAG_PLAYER = "Player";
    public const string TAG_ENEMY = "Enemy";
    public const string TAG_DOUBLE_JUMP = "DoubleJump";

    public const string SETTINGS_SENSITIVITY = "sensitivity";

    public const string GAME_BEST_SCORE = "bestScore";
    public const string GAME_LAST_SCORE = "lastScore";
                        

}

